version: '3'

services:
  strapi:
    container_name: strapi
    build: ./back
    image: sergeapp:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: postgresDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    links:
      - postgresDB:postgresDB
    volumes:
      - ./back:/srv/back
    ports:
      - '1337:1337'
    networks:
      - strapi-app-network
    depends_on:
      - postgresDB
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fastapi.rule=Host(`api.adhumanmobility.com`)'
      - 'traefik.http.routers.fastapi.tls=true'
      - 'traefik.http.routers.fastapi.tls.certresolver=letsencrypt'

  postgresDB:
    image: postgres:12.0-alpine
    container_name: DB
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - strapi-app-network

  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './traefik-public-certificates:/certificates'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.rule=Host(`dashboard.adhumanmobility.com`) && (PathPrefix(`/`)'
      - 'traefik.http.routers.dashboard.tls=true'
      - 'traefik.http.routers.dashboard.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=foxtrot:$$apr1$$RO48PMj9$$Rc8L5j2ivDcWhdLX51J4N/'
    networks:
      - strapi-app-network

networks:
  strapi-app-network:
    driver: bridge
