version: '3.4'

services:
  adhmapi:
    image: registry.git.dotsafe.fr/malineo/adhm/adhmapi:$APP_VERSION
    volumes:
      - adhm_adhmapi_var:/var/www/var
    environment:
      - APP_ENV=prod
      - APP_DOMAIN=$APP_DOMAIN
      - JWT_COOKIE_HP=adhm_chp
      - JWT_COOKIE_SIGNATURE=adhm_cs
    labels:
      - 'roadie.app.host=adhmAPI'

  adhm:
    image: registry.git.dotsafe.fr/malineo/adhm/adhm:$APP_VERSION
    tty: true
    environment:
      - APP_DOMAIN=$APP_DOMAIN
      - JWT_COOKIE_HP=adhm_chp
    labels:
      - 'roadie.app.host=adhm'

  mariadb:
    image: mariadb:10.5.2
    volumes:
      - adhm_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=adhm_password
      - MYSQL_DATABASE=adhm
      - MYSQL_USER=adhm_user
      - MYSQL_PASSWORD=adhm_password
    ports:
      - '127.0.0.1:3307:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=adhm_password
      - UPLOAD_LIMIT=1G
    labels:
      - 'roadie.phpmyadmin.host=PHPMYADMIN'

  mailcatcher:
    image: schickling/mailcatcher
    labels:
      - 'roadie.mailcatcher.host=MAILCATCHER'
      - 'roadie.mailcatcher.port=1080'

volumes:
  adhm_database:
  adhm_adhmapi_var:
