# api/config/packages/api_platform.yaml
api_platform:
  # The title of the API.
  title: 'AdHumanMobility API'

  # The description of the API.
  description: 'API for the website AdHumanMobility.com'

  # The version of the API.
  version: '0.0.0'

  # Set this to false if you want Webby to disappear.
  show_webby: false

  # Specify a name converter to use.
  name_converter: ~

  # Specify an asset package name to use.
  asset_package: null

  # Specify a path name generator to use.
  path_segment_name_generator: 'api_platform.path_segment_name_generator.underscore'

  validator:
    # Enable the serialization of payload fields when a validation error is thrown.
    # If you want to serialize only some payload fields, define them like this: [ severity, anotherPayloadField ]
    serialize_payload_fields: []

    # To enable or disable query parameters validation on collection GET requests
    query_parameter_validation: true

  eager_loading:
    # To enable or disable eager loading.
    enabled: true

    # Fetch only partial data according to serialization groups.
    # If enabled, Doctrine ORM entities will not work as expected if any of the other fields are used.
    fetch_partial: false

    # Max number of joined relations before EagerLoading throws a RuntimeException.
    max_joins: 30

    # Force join on every relation.
    # If disabled, it will only join relations having the EAGER fetch mode.
    force_eager: true

  # Enable the Swagger documentation and export.
  enable_swagger: true

  # Enable Swagger UI.
  enable_swagger_ui: true

  # Enable ReDoc.
  enable_re_doc: false

  # Enable the entrypoint.
  enable_entrypoint: true

  # Enable the docs.
  enable_docs: true

  # Enable the data collector and the WebProfilerBundle integration.
  enable_profiler: true

  swagger:
    versions: [3]
    api_keys:
      JWT:
        name: Authorization
        type: header
    swagger_ui_extra_configuration:
      # Controls the default expansion setting for the operations and tags. It can be 'list' (expands only the tags), 'full' (expands the tags and operations) or 'none' (expands nothing).
      docExpansion: list
      # If set, enables filtering. The top bar will show an edit box that you can use to filter the tagged operations that are shown.
      filter: false
      # You can use any other configuration parameters too.
